# Generated by Django 6.0 on 2025-12-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_workshops', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_speakers', models.PositiveIntegerField(default=0)),
                ('total_budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_attendees', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Metrics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
