# Generated by Django 5.2.10 on 2026-01-21 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attendance_id_alter_registration_id"),
        ("workshops", "0004_alter_workshop_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("registration", "session")},
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["timestamp"], name="attendance__timesta_6c8532_idx"
            ),
        ),
    ]
