# Generated by Django 6.0 on 2025-12-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Business', 'Business'), ('Soft Skills', 'Soft Skills'), ('AI / ML', 'AI / ML'), ('Cloud', 'Cloud'), ('Programming', 'Programming'), ('Design', 'Design'), ('Other', 'Other')], default='Technology', max_length=100),
        ),
    ]
