# Generated by Django 5.2.10 on 2026-01-21 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workshops", "0003_alter_session_id_alter_workshop_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workshop",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AddIndex(
            model_name="workshop",
            index=models.Index(
                fields=["start_date"], name="workshops_w_start_d_e8102b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workshop",
            index=models.Index(
                fields=["category"], name="workshops_w_categor_8a6eb1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workshop",
            index=models.Index(
                fields=["speaker"], name="workshops_w_speaker_0cbd3a_idx"
            ),
        ),
    ]
