# Generated by Django 6.0 on 2025-12-07 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('template_path', models.CharField(default='certificates/templates/default.png', max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='certificates/generated/')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='attendance.registration')),
            ],
        ),
    ]
